application: gitcookin
version: 1
runtime: python
api_version: 1


builtins:
- remote_api: on
- datastore_admin: on

handlers:
    
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /(.*\.(html))
  static_files: static/html/\1
  upload: static/html/(.*\.(html))

- url: /.*
  script: main.py

